spring:
  profiles:
    active: local

  batch:
    # program arguments로 job name이 넘어오면, 해당 값과 일치하는 job만 실행하겠다는 의미
    job:
      # job.name이 있으면, job.name 값을 할당하고, 없으면 NONE을 할당하겠다는 의미
      # NONE이 할당되면, 어떤 배치도 실행하지 않겠다는 의미이다.
      # 즉, 혹시라도 값이 없을때 모든 배치가 실행되지 않도록 막는 역할이다.
      names: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG

chunk-size: 10
batch-size: 1000

--- # local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

--- # mysql
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    hikari:
      # profileSQL=true : Driver에서 전송하는 쿼리를 출력합니다.
      # logger=Slf4JLogger : Driver에서 쿼리 출력시 사용할 Logger를 설정합니다.
      #   - MySQL 드라이버 : 기본값은 System.err 로 출력하도록 설정되어 있기 때문에 필수로 지정해 줘야 합니다.
      #   - MariaDB 드라이버 : Slf4j 를 이용하여 로그를 출력하기 때문에 설정할 필요가 없습니다.
      # maxQuerySizeToLog=999999 : 출력할 쿼리 길이
      #   - MySQL 드라이버 : 기본값이 0 으로 지정되어 있어 값을 설정하지 않을경우 아래처럼 쿼리가 출력되지 않습니다.
      #     - [main] MySQL : [QUERY]  ... (truncated) [Created on: Mon Sep 21 01:03:10 KST 2020, duration: 3,
      #       connection-id: 325, statement-id: 0, resultset-id: 0,
      #       at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)]
      #   - MariaDB 드라이버 : 기본값이 1024 로 지정되어 있습니다. MySQL 드라이버와는 달리 0으로 지정시 쿼리의 글자 제한이 무제한으로 설정됩니다.
      jdbc-url: >
        jdbc:mysql://localhost:9020/spring_batch?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        &profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
      username: root
      password: example
      driver-class-name: com.mysql.cj.jdbc.Driver
